plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'spec/dummy/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 100

Metrics/ModuleLength:
  Max: 100

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'db/migrate/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Lint/EmptyBlock:
  Exclude:
    - 'config/routes.rb'

Rails/DynamicFindBy:
  Exclude:
    - 'spec/repositories/**/*'
    - 'app/repositories/**/*'
    - 'app/controllers/**/*'
    - 'app/services/**/*'

Rails/SkipsModelValidations:
  Enabled: false

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/policies/**/*'
    - 'spec/controllers/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 3

RSpec/NestedGroups:
  Max: 3

RSpec/MultipleMemoizedHelpers:
  Max: 8
